### ISSUE TITLE
no module named 'pydiff'

### ISSUE THREAD

**Issue by yangh0119** [DavisMeee/LighTDiff#1]
![c316a1f83b37c10a5618683c9a5f8a8](https://github.com/user-attachments/assets/ddb741d7-b2cf-4424-a0c4-d1942456b98e)

How to solve this problem?

**Comment by DavisMeee** [comment]
fixed the problem, change all 'pydiff' to 'lightdiff' and the problem will be solved.

**Comment by yangh0119** [comment]
thank you!!!
