### ISSUE TITLE
No object nameed 'LightDIff' found in 'model' registry

### ISSUE THREAD

**Issue by yangh0119** [DavisMeee/LighTDiff#2]
![65294e54101a4dd47d16530ccbd5f62](https://github.com/user-attachments/assets/ada60565-4a56-43f8-90c9-15ef9b500365)
I have changed all 'pydiff' to 'lightdiff', but there are new errors. How should I solve this problem?

**Comment by DavisMeee** [comment]
with lowercase instead of all uppercases I think. Or you can re-clone our fixed version.

**Comment by yangh0119** [comment]
Thank you for your response.！！！
I found the issue. In lightdiff_model.py, the class you registered is LighTDiff, but in train.yaml, you set the type as LightDiff.
![Uploading 075c9121167771433ad034daa3919e1.png…]()

**Comment by yangh0119** [comment]
Thank you for your response.！！！
I found the issue. In lightdiff_model.py, the class you registered is LighTDiff, but in train.yaml, you set the type as LightDiff
![e00c663a2d976c08fc39681ee6929e3](https://github.com/user-attachments/assets/e3200e92-5dcc-4d17-98a8-4f1169eaad8d)
![075c9121167771433ad034daa3919e1](https://github.com/user-attachments/assets/be9bd105-51bd-4df1-88ce-59505911f75f)

**Comment by DavisMeee** [comment]
Oh, thank you so much! I will fix that!

**Comment by yangh0119** [comment]
I'm sorry to bother you again. I encountered this error while training my own model.
![01f7d390302359df838a78090856083](https://github.com/user-attachments/assets/7a9eb571-ca3b-4b4c-bd4d-5e7f6fd30c02)

Here is my train.yml configuration file. How should I resolve this issue?
![47f17f442bd11fc6fc7c568266774c8](https://github.com/user-attachments/assets/60a1e14c-0b66-4a7b-a2c8-a11ccb495fe4)

**Comment by DavisMeee** [comment]
I am not sure about this. It seems like an 'opt' key error. It would help if you dived into to the basicsr code to check out.

**Comment by yangh0119** [comment]
I found it ！！！
The code you submitted has many places where the names have not been changed.
![a07ae312ba613348b19db29e34c6d31](https://github.com/user-attachments/assets/32992b93-694c-46f9-87a8-6d1568217386)

**Comment by yangh0119** [comment]
> I found it ！！！ The code you submitted has many places where the names have not been changed. ![a07ae312ba613348b19db29e34c6d31](https://private-user-images.githubusercontent.com/139987097/350681779-32992b93-694c-46f9-87a8-6d1568217386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NjgyNTAsIm5iZiI6MTcyMTQ2Nzk1MCwicGF0aCI6Ii8xMzk5ODcwOTcvMzUwNjgxNzc5LTMyOTkyYjkzLTY5NGMtNDZmOS04N2E4LTZkMTU2ODIxNzM4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwOTMyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmY3ZWIxMDg3MzkzZjUxYWEyYThjZjUwNDVkMTdkZDhmMTgyYjA1NWEzNTUzN2VjYTQ0Y2VjODBhODA1NzEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J0HzTYrtJv1DIpi5ySDWCpSBdXWGyyk1qKifKRK6CuI)

This way it can be trained.
