### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by linyteating** [DavisMeee/LighTDiff#3]
你好，不知道是不是因为图片输入路径的原因，导致我们生成的图片非常奇怪。看你们的文档并没有涉及到这个问题，想请教一下应该怎么解决。
![dd41287b9c8b4fa3b5673078eea1b13](https://github.com/user-attachments/assets/f5603a88-6638-4516-a6c5-21459ef84749)
![4438dc295a34d3c277f9fdc86163af4](https://github.com/user-attachments/assets/04833d6f-7bbb-45bb-bd6c-865c44eed2bc)

**Comment by linyteating** [comment]
发邮件请教和申请加微信，都没有回复

**Comment by DavisMeee** [comment]
Sorry for the late respond, but I don't know what happened to this with a limited screenshot. I would like to know whether you have changed any codes from the original.

**Comment by linyteating** [comment]
你好 我没改过代码 请问上面那几个路径应该放什么内容？

**Comment by DavisMeee** [comment]
Let me use LOL dataset as an example:
input_root : ./our485/low
gt_root : ./our485/high

**Comment by linyteating** [comment]
![Uploading 2ffcf98970bd7c3945b1b1e522fd322.png…]()
你好 我发现C:\Users\Administrator\Desktop\LighTDiff-main\BasicSR-light\docs 这个路径下有详细的配置要求，但是似乎并没有关于Lightdiff这个模型的配置要求，BasicSR-light\docs这个文件夹里面也只有关于超分要用什么数据集，并没有涉及到Lightdiff要用什么数据集，所以想向你请教一下怎么解决，应该放什么数据集比较合适。我放了一组高低光照匹配的数据集，但是生成的图片是这样的失真图片，感到非常奇怪。

**Comment by linyteating** [comment]
![Uploading 2ffcf98970bd7c3945b1b1e522fd322.png…]()

**Comment by linyteating** [comment]
你好，我发现LighTDiff-main\LighTDiff\BasicSR\options\test只有这个文件夹里面有超分的预训练模型，但是LighTDiff-main\LighTDiff\lightdiff这个文件夹下面没有关于diffusion的预训练模型，是没有吗？

**Comment by DavisMeee** [comment]
Sorry, there's no pretraining lightdiff model in our light-BasicSR. Basic-SR only has pre-training weights for classic models.

**Comment by DavisMeee** [comment]
BTW your upload images are broken and I am afraid that I cannot help with these broken images.
I don't know what happens, but I am sure my code is reproducible.

**Comment by linyteating** [comment]
LighTDiff: Surgical Endoscopic Image Low-Light
Enhancement with T-Diffusion
你好，上面这篇论文是你们所编撰的，那既然没有lightdiff的预训练模型，那
你们是怎么实现代码的？

**Comment by linyteating** [comment]
方便拉我进你们的交流群吗？QQ群满了，微信群加了负责人，到现在都还没有通过。

**Comment by DavisMeee** [comment]
We have utilized the library BasicSR to implement lightdiff framework. We are still preparing it and the pre-trained model will be released later. This model is fully retrainable and takes only 4 hours to train with batch_size = 8.

**Comment by linyteating** [comment]
你好 LighTDiff-main\experiments\training_archived_20240901_173614\models 我想问一下为什么训练完这里面的model是空的，是我们哪里出错了吗？还是你们代码没有输出出来?

**Comment by DavisMeee** [comment]
Right, first I don’t know what really happened with these single description. Then this code is reproducible and already verified by the others( like previous issues, they all succeed reproduced lightdiff). It must be something wrong with your env or code even database. Please check your code and debug it by yourself. Frankly speaking, this is not in my charge, thank you for understanding.

**Comment by linyteating** [comment]
好的 谢谢
