### ISSUE TITLE
Instructions for code implementation

### ISSUE THREAD

**Issue by ntdat8324** [DavisMeee/LighTDiff#4]
Hello,

Thank you very much for your effort.

I am building a Pre-processing and Enhancement for Endo image. May i have guide to excute code? Please
I dont know enhance my image :((
I'm looking forward to recieving your respond.

Regards.

**Comment by DavisMeee** [comment]
You can pre-process the image in several ways, like adjusting exposure, gamma value, and brightness.
I think there are some functions set in skimage and PIL.

**Comment by ntdat8324** [comment]
> You can pre-process the image in several ways, like adjusting exposure, gamma value, and brightness. I think there are some functions set in skimage and PIL.

What I mean is I need guidance on how to set up and run tests on my dataset. Currently, I can't find the 'pretrained weights' or the model zoo, and I would also like to better understand how to use the test.yml. I have referred to and looked through the LLCaps paper and the GitHub repo, but there are no 'pretrained weights' or model zoo.
I am very grateful for your efforts.
