### ISSUE TITLE
Could you offer your  method code or EndoVis17 dataset for transferring normal images to low-light images

### ISSUE THREAD

**Issue by vitwei** [DavisMeee/LighTDiff#5]
(*^_^*)

**Comment by DavisMeee** [comment]
Sorry, I am quite busy right now, but I will release the related dataset after MICCAI 2024. Thank you for your patience.
The related method can be found in this paper: (https://arxiv.org/abs/1511.03995)
K.G Lore et al.: Llnet: A deep autoencoder approach to natural low-light image enhancement. Pattern Recognition 61, 650–662, 2017.
