### ISSUE TITLE
test and inference

### ISSUE THREAD

**Issue by yjy-png** [DavisMeee/LighTDiff#9]
Hello, I've noticed that there seems to be an issue with the testing in the code. When I ran your tests, the output was just noise images. Additionally, I couldn't find the inference files for the code. Could you please upload them?

**Comment by DavisMeee** [comment]
I am sure it is right. You may forget to set the checkpoint path in the file.

**Comment by yjy-png** [comment]
# path
path:
  pretrain_network_g: E:\code\model\LighTDiff\experiments\training_archived_20241216_092250\models\net_g_latest.pth
  param_key_g: params
  strict_load_g: False
  pretrain_network_d: ~
  resume_state: ~
  ignore_resume_networks: ['network_identity'] 
Is this setup incorrect

**Comment by DavisMeee** [comment]
Hmmm, it looks good to me. That's weird. But this code is replicable. You may need to find the bug.

**Comment by yjy-png** [comment]
Thank you very much for your help, I have already solved the problem
